# Generated by Django 3.2.19 on 2023-05-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='../defaultprofile_yqihgb.webp', upload_to='profiles/'),
        ),
    ]
