# Generated by Django 3.2.19 on 2023-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230508_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileicon',
            field=models.CharField(default='dice', max_length=25),
        ),
    ]
