# Generated by Django 3.2.19 on 2023-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profileicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileicon',
            field=models.CharField(choices=[('puzzle-piece', 'Puzzle'), ('dice', 'Dice'), ('chess', 'Chess'), ('hat-wizard', 'Wizard'), ('book-skull', 'Pirate')], default='dice', max_length=25),
        ),
    ]
