# Generated by Django 3.2.19 on 2023-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
