# Generated by Django 3.2.19 on 2023-06-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-lastupdated']},
        ),
    ]
