# Generated by Django 3.2.19 on 2023-06-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='lastupdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
