# Generated by Django 3.2.19 on 2023-05-16 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tags', models.TextField(blank=True)),
                ('minplayers', models.IntegerField(default=1)),
                ('maxplayers', models.IntegerField(default=4)),
                ('playtime', models.CharField(choices=[(0, '<5'), (5, '5-10'), (10, '10-20'), (20, '20-40'), (40, '40-90'), (90, '90+')], default=0, max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
