# Generated by Django 3.2.19 on 2023-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='playtime',
            field=models.IntegerField(choices=[(0, '<5'), (5, '5-10'), (10, '10-20'), (20, '20-40'), (40, '40-90'), (90, '90+')], default=0),
        ),
    ]
